name: LearningX
favicon: null
layout_spectrum: 0.19822
typography_spectrum: 0.27074
title: Learning Experience Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0086d8'
    - '#abceda'
    - '#39261e'
    - '#977238'
  brandStrength: 0.6875
  lightness: 0.2739040032029152
  saturation: 0.375
  rhythmicContrast: 0.3821688808966428
purpose: []
